# Generated by Django 2.1.3 on 2019-06-10 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类别名')),
                ('is_valid', models.BooleanField(default=True, verbose_name='有效')),
                ('new_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='Xuanzeti',
            fields=[
                ('erp_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_valid', models.BooleanField(default=True, verbose_name='有效')),
                ('wenti', models.TextField(default='', max_length=256)),
                ('xuanxiang_a', models.TextField(default='', max_length=256)),
                ('xuanxiang_b', models.TextField(default='', max_length=256)),
                ('xuanxiang_c', models.TextField(default='', max_length=256)),
                ('xuanxiang_d', models.TextField(default='', max_length=256)),
                ('daan', models.CharField(default='a', max_length=6)),
                ('new_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shiti.Category', verbose_name='类别')),
            ],
            options={
                'verbose_name': '单选题',
                'verbose_name_plural': '单选题',
            },
        ),
    ]
